import * as vscode from "vscode";
import { SymbolStore } from "../symbolStore";
import { lookupBuiltin } from "../builtins";
import { lookupDoc, docUrl } from "../dictionary";

const IDENTIFIER = /[a-zA-Z_#][a-zA-Z0-9_?!#%:-]*/;

export class NetLogoHoverProvider implements vscode.HoverProvider {
  constructor(private symbolStore: SymbolStore) {}

  provideHover(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.Hover | undefined {
    this.symbolStore.ensureDocumentParsed(document);

    const wordRange = document.getWordRangeAtPosition(position, IDENTIFIER);
    if (!wordRange) return undefined;

    const word = document.getText(wordRange);
    const lower = word.toLowerCase();

    // --- user-defined symbols take priority ---
    const userSymbol = this.symbolStore
      .getVisibleSymbols(document.uri)
      .find((s) => s.name.toLowerCase() === lower);

    if (userSymbol) {
      const md = new vscode.MarkdownString();
      md.isTrusted = true;

      if (userSymbol.kind === "procedure" || userSymbol.kind === "reporter") {
        const params =
          userSymbol.parameters.length > 0
            ? ` [${userSymbol.parameters.join(" ")}]`
            : "";
        const keyword = userSymbol.kind === "procedure" ? "to" : "to-report";
        md.appendCodeblock(`${keyword} ${userSymbol.name}${params}`, "netlogo");
      } else if (userSymbol.kind === "breed") {
        md.appendCodeblock(
          `breed [${userSymbol.name} ${userSymbol.extra || ""}]`,
          "netlogo"
        );
      } else if (userSymbol.kind === "link-breed") {
        md.appendCodeblock(
          `link-breed [${userSymbol.name} ${userSymbol.extra || ""}]`,
          "netlogo"
        );
      } else if (userSymbol.kind === "global") {
        md.appendCodeblock(`(global) ${userSymbol.name}`, "netlogo");
      } else {
        md.appendCodeblock(
          `(${userSymbol.kind}) ${userSymbol.name}`,
          "netlogo"
        );
        if (userSymbol.extra) {
          md.appendMarkdown(`\n\nOwner: \`${userSymbol.extra}\``);
        }
      }

      if (userSymbol.documentation) {
        md.appendMarkdown(`\n\n---\n\n${userSymbol.documentation}`);
      }

      const loc = userSymbol.location;
      const fileName = loc.uri.fsPath.split(/[\\/]/).pop();
      md.appendMarkdown(
        `\n\n*Defined in ${fileName}:${loc.range.start.line + 1}*`
      );
      return new vscode.Hover(md, wordRange);
    }

    // --- breed-generated primitives ---
    const generated = this.symbolStore
      .getGeneratedPrimitives(document.uri)
      .find((g) => g.name.toLowerCase() === lower);
    if (generated) {
      const md = new vscode.MarkdownString();
      md.appendCodeblock(`(${generated.kind}) ${generated.name}`, "netlogo");
      md.appendMarkdown(`\n\n${generated.description}`);
      md.appendMarkdown(
        `\n\n*Generated by \`breed [${generated.breed} ...]\`*`
      );
      return new vscode.Hover(md, wordRange);
    }

    // --- extension primitives ---
    const extPrim = this.symbolStore
      .getExtensionPrimitives(document.uri)
      .find((e) => e.name.toLowerCase() === lower);
    if (extPrim) {
      const md = new vscode.MarkdownString();
      md.appendCodeblock(`(${extPrim.kind}) ${extPrim.name}`, "netlogo");
      md.appendMarkdown(`\n\n${extPrim.description}`);
      const ext = extPrim.name.split(":")[0];
      md.appendMarkdown(`\n\n*From the \`${ext}\` extension*`);
      return new vscode.Hover(md, wordRange);
    }

    // --- built-in primitives, documented from the official dictionary ---
    const doc = lookupDoc(word);
    const builtin = lookupBuiltin(word);
    if (doc || builtin) {
      const md = new vscode.MarkdownString();
      md.isTrusted = true;

      if (doc?.syntax.length) {
        md.appendCodeblock(doc.syntax.join("\n"), "netlogo");
      } else if (builtin) {
        md.appendCodeblock(`(${builtin.kind}) ${builtin.name}`, "netlogo");
      }

      const description = doc?.description || builtin?.description || "";
      if (description) {
        md.appendMarkdown(`\n\n${description}`);
      }

      if (doc?.example) {
        md.appendMarkdown(`\n\n**Example**`);
        md.appendCodeblock(doc.example, "netlogo");
      }

      const footer: string[] = [];
      if (builtin) footer.push(`NetLogo built-in ${builtin.kind}`);
      if (doc?.since) footer.push(`since ${doc.since}`);
      if (footer.length) {
        md.appendMarkdown(`\n\n*${footer.join(", ")}*`);
      }
      if (doc) {
        md.appendMarkdown(`\n\n[NetLogo dictionary](${docUrl(doc)})`);
      }
      return new vscode.Hover(md, wordRange);
    }

    return undefined;
  }
}
