/**
 * NetLogo built-in primitives: keywords, constants, commands, and reporters.
 */

export type BuiltinKind = "keyword" | "constant" | "command" | "reporter";

export interface Builtin {
  name: string;
  kind: BuiltinKind;
  description: string;
}

/** NetLogo keywords (structural) */
export const KEYWORDS: Builtin[] = [
    { name: "to", kind: "keyword", description: "Define a procedure" },
    { name: "to-report", kind: "keyword", description: "Define a reporter procedure" },
    { name: "end", kind: "keyword", description: "End a procedure definition" },
    { name: "globals", kind: "keyword", description: "Declare global variables" },
    { name: "breed", kind: "keyword", description: "Declare a turtle breed" },
    { name: "directed-link-breed", kind: "keyword", description: "Declare a directed link breed" },
    { name: "undirected-link-breed", kind: "keyword", description: "Declare an undirected link breed" },
    { name: "turtles-own", kind: "keyword", description: "Declare variables for all turtles" },
    { name: "patches-own", kind: "keyword", description: "Declare variables for all patches" },
    { name: "links-own", kind: "keyword", description: "Declare variables for all links" },
    { name: "extensions", kind: "keyword", description: "Load NetLogo extensions" },
    { name: "__includes", kind: "keyword", description: "Include external NetLogo source files" },
];
/** NetLogo built-in constants */
export const CONSTANTS: Builtin[] = [
    { name: "true", kind: "constant", description: "Boolean true" },
    { name: "false", kind: "constant", description: "Boolean false" },
    { name: "nobody", kind: "constant", description: "No agent" },
    { name: "e", kind: "constant", description: "Euler's number (2.71828...)" },
    { name: "pi", kind: "constant", description: "Pi (3.14159...)" },
    { name: "gray", kind: "constant", description: "Color constant (5)" },
    { name: "grey", kind: "constant", description: "Color constant (5)" },
    { name: "red", kind: "constant", description: "Color constant (15)" },
    { name: "orange", kind: "constant", description: "Color constant (25)" },
    { name: "brown", kind: "constant", description: "Color constant (35)" },
    { name: "yellow", kind: "constant", description: "Color constant (45)" },
    { name: "green", kind: "constant", description: "Color constant (55)" },
    { name: "lime", kind: "constant", description: "Color constant (65)" },
    { name: "turquoise", kind: "constant", description: "Color constant (75)" },
    { name: "cyan", kind: "constant", description: "Color constant (85)" },
    { name: "sky", kind: "constant", description: "Color constant (95)" },
    { name: "blue", kind: "constant", description: "Color constant (105)" },
    { name: "violet", kind: "constant", description: "Color constant (115)" },
    { name: "magenta", kind: "constant", description: "Color constant (125)" },
    { name: "pink", kind: "constant", description: "Color constant (135)" },
    { name: "black", kind: "constant", description: "Color constant (0)" },
    { name: "white", kind: "constant", description: "Color constant (9.9)" },
];
/** NetLogo built-in commands */
export const COMMANDS: Builtin[] = [
    { name: "ask", kind: "command", description: "Ask agents in an agentset to run commands" },
    { name: "ask-concurrent", kind: "command", description: "Ask agents to run commands concurrently" },
    { name: "auto-plot-off", kind: "command", description: "Turn off automatic plot scaling" },
    { name: "auto-plot-on", kind: "command", description: "Turn on automatic plot scaling" },
    { name: "auto-plot-x-off", kind: "command", description: "Turn off auto-scaling of x-axis" },
    { name: "auto-plot-x-on", kind: "command", description: "Turn on auto-scaling of x-axis" },
    { name: "auto-plot-y-off", kind: "command", description: "Turn off auto-scaling of y-axis" },
    { name: "auto-plot-y-on", kind: "command", description: "Turn on auto-scaling of y-axis" },
    { name: "back", kind: "command", description: "Move turtle backward by number of steps" },
    { name: "bk", kind: "command", description: "Abbreviation for back" },
    { name: "beep", kind: "command", description: "Play a beep sound" },
    { name: "carefully", kind: "command", description: "Run commands; if error occurs, run alternative commands" },
    { name: "clear-all", kind: "command", description: "Clear all turtles, patches, globals, and plots" },
    { name: "ca", kind: "command", description: "Abbreviation for clear-all" },
    { name: "clear-all-plots", kind: "command", description: "Clear all plots" },
    { name: "clear-drawing", kind: "command", description: "Clear the drawing layer" },
    { name: "cd", kind: "command", description: "Abbreviation for clear-drawing" },
    { name: "clear-globals", kind: "command", description: "Reset all global variables to 0" },
    { name: "clear-links", kind: "command", description: "Kill all links" },
    { name: "clear-output", kind: "command", description: "Clear the output area" },
    { name: "clear-patches", kind: "command", description: "Reset all patches to default state" },
    { name: "cp", kind: "command", description: "Abbreviation for clear-patches" },
    { name: "clear-plot", kind: "command", description: "Clear the current plot" },
    { name: "clear-ticks", kind: "command", description: "Clear the tick counter" },
    { name: "clear-turtles", kind: "command", description: "Kill all turtles" },
    { name: "ct", kind: "command", description: "Abbreviation for clear-turtles" },
    { name: "create-link-from", kind: "command", description: "Create a directed link from another turtle" },
    { name: "create-link-to", kind: "command", description: "Create a directed link to another turtle" },
    { name: "create-link-with", kind: "command", description: "Create an undirected link with another turtle" },
    { name: "create-links-from", kind: "command", description: "Create directed links from a set of turtles" },
    { name: "create-links-to", kind: "command", description: "Create directed links to a set of turtles" },
    { name: "create-links-with", kind: "command", description: "Create undirected links with a set of turtles" },
    { name: "create-ordered-turtles", kind: "command", description: "Create turtles evenly spaced around the origin" },
    { name: "cro", kind: "command", description: "Abbreviation for create-ordered-turtles" },
    { name: "create-turtles", kind: "command", description: "Create a number of new turtles" },
    { name: "crt", kind: "command", description: "Abbreviation for create-turtles" },
    { name: "create-temporary-plot-pen", kind: "command", description: "Create a temporary pen in the current plot" },
    { name: "die", kind: "command", description: "Remove the calling agent" },
    { name: "diffuse", kind: "command", description: "Diffuse a patch variable to 8 neighboring patches" },
    { name: "diffuse4", kind: "command", description: "Diffuse a patch variable to 4 neighboring patches" },
    { name: "display", kind: "command", description: "Force a view update" },
    { name: "downhill", kind: "command", description: "Move turtle to the lowest-valued neighboring patch (8)" },
    { name: "downhill4", kind: "command", description: "Move turtle to the lowest-valued neighboring patch (4)" },
    { name: "error", kind: "command", description: "Cause a runtime error with the given message" },
    { name: "every", kind: "command", description: "Run commands at most once every N seconds" },
    { name: "export-all-plots", kind: "command", description: "Export all plot data to a CSV file" },
    { name: "export-interface", kind: "command", description: "Export the interface to an image file" },
    { name: "export-output", kind: "command", description: "Export the output area to a file" },
    { name: "export-plot", kind: "command", description: "Export a plot to a CSV file" },
    { name: "export-view", kind: "command", description: "Export the view to an image file" },
    { name: "export-world", kind: "command", description: "Export the entire world state to a file" },
    { name: "face", kind: "command", description: "Turn turtle to face another agent" },
    { name: "facexy", kind: "command", description: "Turn turtle to face a point (x, y)" },
    { name: "file-close", kind: "command", description: "Close the currently open file" },
    { name: "file-close-all", kind: "command", description: "Close all open files" },
    { name: "file-delete", kind: "command", description: "Delete a file" },
    { name: "file-flush", kind: "command", description: "Flush the file output buffer" },
    { name: "file-open", kind: "command", description: "Open a file for reading or writing" },
    { name: "file-print", kind: "command", description: "Print a value to the open file followed by newline" },
    { name: "file-show", kind: "command", description: "Print a value to the open file (with agent context)" },
    { name: "file-type", kind: "command", description: "Print a value to the open file without newline" },
    { name: "file-write", kind: "command", description: "Write a value to the open file in readable format" },
    { name: "follow", kind: "command", description: "Follow a turtle in the view" },
    { name: "follow-me", kind: "command", description: "Make the view follow this turtle" },
    { name: "foreach", kind: "command", description: "Iterate over list(s) running commands for each item" },
    { name: "forward", kind: "command", description: "Move turtle forward by number of steps" },
    { name: "fd", kind: "command", description: "Abbreviation for forward" },
    { name: "hatch", kind: "command", description: "Create copies of the calling turtle" },
    { name: "hide-link", kind: "command", description: "Make this link invisible" },
    { name: "hide-turtle", kind: "command", description: "Make this turtle invisible" },
    { name: "ht", kind: "command", description: "Abbreviation for hide-turtle" },
    { name: "histogram", kind: "command", description: "Plot a histogram of values from a list" },
    { name: "home", kind: "command", description: "Move turtle to the origin (0, 0)" },
    { name: "if", kind: "command", description: "If condition is true, run commands" },
    { name: "ifelse", kind: "command", description: "If condition is true run first block, otherwise second" },
    { name: "import-drawing", kind: "command", description: "Import an image into the drawing layer" },
    { name: "import-pcolors", kind: "command", description: "Import an image as patch colors" },
    { name: "import-pcolors-rgb", kind: "command", description: "Import an image as patch colors (RGB)" },
    { name: "import-world", kind: "command", description: "Import a saved world state" },
    { name: "inspect", kind: "command", description: "Open an agent monitor" },
    { name: "jump", kind: "command", description: "Move turtle forward (may land between patches)" },
    { name: "layout-circle", kind: "command", description: "Arrange turtles in a circle" },
    { name: "layout-radial", kind: "command", description: "Arrange turtles in a radial tree layout" },
    { name: "layout-spring", kind: "command", description: "Arrange turtles using spring-based algorithm" },
    { name: "layout-tutte", kind: "command", description: "Arrange turtles using Tutte embedding" },
    { name: "left", kind: "command", description: "Turn turtle left by degrees" },
    { name: "lt", kind: "command", description: "Abbreviation for left" },
    { name: "let", kind: "command", description: "Define a local variable" },
    { name: "loop", kind: "command", description: "Repeat commands forever (use stop to exit)" },
    { name: "move-to", kind: "command", description: "Move turtle to the same location as another agent" },
    { name: "no-display", kind: "command", description: "Suppress view updates" },
    { name: "output-print", kind: "command", description: "Print to the output area with newline" },
    { name: "output-show", kind: "command", description: "Print to the output area (with agent context)" },
    { name: "output-type", kind: "command", description: "Print to the output area without newline" },
    { name: "output-write", kind: "command", description: "Write to the output area in readable format" },
    { name: "pen-down", kind: "command", description: "Start drawing as turtle moves" },
    { name: "pd", kind: "command", description: "Abbreviation for pen-down" },
    { name: "pen-erase", kind: "command", description: "Erase drawing as turtle moves" },
    { name: "pe", kind: "command", description: "Abbreviation for pen-erase" },
    { name: "pen-up", kind: "command", description: "Stop drawing as turtle moves" },
    { name: "pu", kind: "command", description: "Abbreviation for pen-up" },
    { name: "plot", kind: "command", description: "Plot a point on the current plot" },
    { name: "plot-pen-down", kind: "command", description: "Lower the plot pen (start drawing)" },
    { name: "plot-pen-reset", kind: "command", description: "Reset the current plot pen" },
    { name: "plot-pen-up", kind: "command", description: "Raise the plot pen (stop drawing)" },
    { name: "plotxy", kind: "command", description: "Plot a point at specific x, y coordinates" },
    { name: "print", kind: "command", description: "Print a value to the command center" },
    { name: "random-seed", kind: "command", description: "Set the random number generator seed" },
    { name: "repeat", kind: "command", description: "Run commands a specified number of times" },
    { name: "report", kind: "command", description: "Return a value from a reporter procedure" },
    { name: "reset-perspective", kind: "command", description: "Return view to default perspective" },
    { name: "rp", kind: "command", description: "Abbreviation for reset-perspective" },
    { name: "reset-ticks", kind: "command", description: "Reset the tick counter to 0 and update plots" },
    { name: "reset-timer", kind: "command", description: "Reset the timer to 0" },
    { name: "resize-world", kind: "command", description: "Change the size of the world" },
    { name: "ride", kind: "command", description: "Ride a turtle (first-person perspective)" },
    { name: "ride-me", kind: "command", description: "Switch to riding perspective of this turtle" },
    { name: "right", kind: "command", description: "Turn turtle right by degrees" },
    { name: "rt", kind: "command", description: "Abbreviation for right" },
    { name: "run", kind: "command", description: "Run a string as commands, or run an anonymous command" },
    { name: "set", kind: "command", description: "Set a variable to a new value" },
    { name: "set-current-directory", kind: "command", description: "Set the working directory for file operations" },
    { name: "set-current-plot", kind: "command", description: "Set which plot is the current plot" },
    { name: "set-current-plot-pen", kind: "command", description: "Set which pen is the current plot pen" },
    { name: "set-default-shape", kind: "command", description: "Set the default shape for a breed" },
    { name: "set-histogram-num-bars", kind: "command", description: "Set the number of bars for histograms" },
    { name: "set-patch-size", kind: "command", description: "Set the pixel size of patches in the view" },
    { name: "set-plot-background-color", kind: "command", description: "Set the background color of the current plot" },
    { name: "set-plot-pen-color", kind: "command", description: "Set the color of the current plot pen" },
    { name: "set-plot-pen-interval", kind: "command", description: "Set the x-interval of the current plot pen" },
    { name: "set-plot-pen-mode", kind: "command", description: "Set the drawing mode of the current plot pen" },
    { name: "set-plot-x-range", kind: "command", description: "Set the x-axis range of the current plot" },
    { name: "set-plot-y-range", kind: "command", description: "Set the y-axis range of the current plot" },
    { name: "setup-plots", kind: "command", description: "Run all plot setup commands" },
    { name: "setxy", kind: "command", description: "Set turtle's x and y coordinates" },
    { name: "show", kind: "command", description: "Print a value with agent context to the command center" },
    { name: "show-link", kind: "command", description: "Make this link visible" },
    { name: "show-turtle", kind: "command", description: "Make this turtle visible" },
    { name: "st", kind: "command", description: "Abbreviation for show-turtle" },
    { name: "sprout", kind: "command", description: "Create turtles on this patch" },
    { name: "stamp", kind: "command", description: "Stamp agent's shape on the drawing layer" },
    { name: "stamp-erase", kind: "command", description: "Erase agent's shape from the drawing layer" },
    { name: "stop", kind: "command", description: "Exit the current procedure" },
    { name: "tick", kind: "command", description: "Advance the tick counter by 1 and update plots" },
    { name: "tick-advance", kind: "command", description: "Advance the tick counter by a given amount" },
    { name: "tie", kind: "command", description: "Tie this link's endpoints together" },
    { name: "type", kind: "command", description: "Print a value without newline" },
    { name: "untie", kind: "command", description: "Untie this link's endpoints" },
    { name: "update-plots", kind: "command", description: "Run all plot update commands" },
    { name: "uphill", kind: "command", description: "Move turtle to highest-valued neighboring patch (8)" },
    { name: "uphill4", kind: "command", description: "Move turtle to highest-valued neighboring patch (4)" },
    { name: "user-message", kind: "command", description: "Show a message dialog to the user" },
    { name: "wait", kind: "command", description: "Wait a specified number of seconds" },
    { name: "watch", kind: "command", description: "Watch a specific agent in the view" },
    { name: "watch-me", kind: "command", description: "Make the view watch this agent" },
    { name: "while", kind: "command", description: "Repeat commands while a condition is true" },
    { name: "with-local-randomness", kind: "command", description: "Run commands without affecting the random state" },
    { name: "without-interruption", kind: "command", description: "Run commands atomically (without interruption)" },
    { name: "write", kind: "command", description: "Print a value in readable format" },
];
/** NetLogo built-in reporters */
export const REPORTERS: Builtin[] = [
    { name: "abs", kind: "reporter", description: "Report the absolute value of a number" },
    { name: "acos", kind: "reporter", description: "Report the arc cosine (in degrees)" },
    { name: "all?", kind: "reporter", description: "Report true if all agents in agentset satisfy condition" },
    { name: "and", kind: "reporter", description: "Logical AND of two boolean values" },
    { name: "any?", kind: "reporter", description: "Report true if the agentset is non-empty" },
    { name: "approximate-hsb", kind: "reporter", description: "Report NetLogo color closest to given HSB values" },
    { name: "approximate-rgb", kind: "reporter", description: "Report NetLogo color closest to given RGB values" },
    { name: "asin", kind: "reporter", description: "Report the arc sine (in degrees)" },
    { name: "at-points", kind: "reporter", description: "Report agentset at given relative coordinates" },
    { name: "atan", kind: "reporter", description: "Report the arc tangent (in degrees)" },
    { name: "base-colors", kind: "reporter", description: "Report list of 14 base hue colors" },
    { name: "behaviorspace-experiment-name", kind: "reporter", description: "Report the name of the current BehaviorSpace experiment" },
    { name: "behaviorspace-run-number", kind: "reporter", description: "Report the current BehaviorSpace run number" },
    { name: "both-ends", kind: "reporter", description: "Report the two turtles connected by this link" },
    { name: "but-first", kind: "reporter", description: "Report all but the first element of a list or string" },
    { name: "bf", kind: "reporter", description: "Abbreviation for but-first" },
    { name: "but-last", kind: "reporter", description: "Report all but the last element of a list or string" },
    { name: "bl", kind: "reporter", description: "Abbreviation for but-last" },
    { name: "can-move?", kind: "reporter", description: "Report true if turtle can move the given distance" },
    { name: "ceiling", kind: "reporter", description: "Report the smallest integer >= the number" },
    { name: "cos", kind: "reporter", description: "Report the cosine of an angle (in degrees)" },
    { name: "count", kind: "reporter", description: "Report the number of agents in an agentset" },
    { name: "date-and-time", kind: "reporter", description: "Report the current date and time as a string" },
    { name: "distance", kind: "reporter", description: "Report distance to another agent" },
    { name: "distancexy", kind: "reporter", description: "Report distance to a point (x, y)" },
    { name: "dx", kind: "reporter", description: "Report the x-increment for one step in current heading" },
    { name: "dy", kind: "reporter", description: "Report the y-increment for one step in current heading" },
    { name: "empty?", kind: "reporter", description: "Report true if the list or string is empty" },
    { name: "end1", kind: "reporter", description: "Report the first endpoint of a link" },
    { name: "end2", kind: "reporter", description: "Report the second endpoint of a link" },
    { name: "error-message", kind: "reporter", description: "Report the error message from a carefully block" },
    { name: "exp", kind: "reporter", description: "Report e raised to the given power" },
    { name: "extract-hsb", kind: "reporter", description: "Report HSB components of a NetLogo color" },
    { name: "extract-rgb", kind: "reporter", description: "Report RGB components of a NetLogo color" },
    { name: "file-at-end?", kind: "reporter", description: "Report true if end of file has been reached" },
    { name: "file-exists?", kind: "reporter", description: "Report true if the given file exists" },
    { name: "file-read", kind: "reporter", description: "Read a value from the currently open file" },
    { name: "file-read-characters", kind: "reporter", description: "Read a number of characters from the open file" },
    { name: "file-read-line", kind: "reporter", description: "Read a line from the currently open file" },
    { name: "filter", kind: "reporter", description: "Report items from a list that satisfy a condition" },
    { name: "first", kind: "reporter", description: "Report the first element of a list or string" },
    { name: "floor", kind: "reporter", description: "Report the largest integer <= the number" },
    { name: "fput", kind: "reporter", description: "Add an item to the front of a list" },
    { name: "hsb", kind: "reporter", description: "Report a color from HSB values" },
    { name: "ifelse-value", kind: "reporter", description: "Report one of two values depending on condition" },
    { name: "in-cone", kind: "reporter", description: "Report agents within a cone of vision" },
    { name: "in-link-from", kind: "reporter", description: "Report the directed link from another turtle to this one" },
    { name: "in-link-neighbor?", kind: "reporter", description: "Report true if there is a directed link from the other turtle" },
    { name: "in-link-neighbors", kind: "reporter", description: "Report the agentset of turtles with directed links to this turtle" },
    { name: "in-radius", kind: "reporter", description: "Report agents within a given radius" },
    { name: "int", kind: "reporter", description: "Report the integer part of a number (truncate toward 0)" },
    { name: "is-agent?", kind: "reporter", description: "Report true if the value is an agent" },
    { name: "is-agentset?", kind: "reporter", description: "Report true if the value is an agentset" },
    { name: "is-boolean?", kind: "reporter", description: "Report true if the value is a boolean" },
    { name: "is-directed-link?", kind: "reporter", description: "Report true if the link is directed" },
    { name: "is-link?", kind: "reporter", description: "Report true if the value is a link" },
    { name: "is-link-set?", kind: "reporter", description: "Report true if the value is a link agentset" },
    { name: "is-list?", kind: "reporter", description: "Report true if the value is a list" },
    { name: "is-number?", kind: "reporter", description: "Report true if the value is a number" },
    { name: "is-patch?", kind: "reporter", description: "Report true if the value is a patch" },
    { name: "is-patch-set?", kind: "reporter", description: "Report true if the value is a patch agentset" },
    { name: "is-string?", kind: "reporter", description: "Report true if the value is a string" },
    { name: "is-turtle?", kind: "reporter", description: "Report true if the value is a turtle" },
    { name: "is-turtle-set?", kind: "reporter", description: "Report true if the value is a turtle agentset" },
    { name: "is-undirected-link?", kind: "reporter", description: "Report true if the link is undirected" },
    { name: "is-anonymous-command?", kind: "reporter", description: "Report true if the value is an anonymous command" },
    { name: "is-anonymous-reporter?", kind: "reporter", description: "Report true if the value is an anonymous reporter" },
    { name: "item", kind: "reporter", description: "Report the item at an index in a list or string" },
    { name: "last", kind: "reporter", description: "Report the last element of a list or string" },
    { name: "length", kind: "reporter", description: "Report the length of a list or string" },
    { name: "link", kind: "reporter", description: "Report the link between two turtles" },
    { name: "link-heading", kind: "reporter", description: "Report the heading of this link" },
    { name: "link-length", kind: "reporter", description: "Report the length of this link" },
    { name: "link-neighbor?", kind: "reporter", description: "Report true if there is a link with another turtle" },
    { name: "link-neighbors", kind: "reporter", description: "Report agentset of turtles linked to this turtle" },
    { name: "link-set", kind: "reporter", description: "Report an agentset of the given links" },
    { name: "link-shapes", kind: "reporter", description: "Report list of available link shapes" },
    { name: "link-with", kind: "reporter", description: "Report the undirected link with another turtle" },
    { name: "links", kind: "reporter", description: "Report the agentset of all links" },
    { name: "list", kind: "reporter", description: "Report a list of the given items" },
    { name: "ln", kind: "reporter", description: "Report the natural logarithm" },
    { name: "log", kind: "reporter", description: "Report the logarithm (base and number)" },
    { name: "lput", kind: "reporter", description: "Add an item to the end of a list" },
    { name: "map", kind: "reporter", description: "Apply a reporter to each item in list(s)" },
    { name: "max", kind: "reporter", description: "Report the maximum value in a list" },
    { name: "max-n-of", kind: "reporter", description: "Report the N agents with highest value" },
    { name: "max-one-of", kind: "reporter", description: "Report the agent with the highest value" },
    { name: "max-pxcor", kind: "reporter", description: "Report the maximum x-coordinate of patches" },
    { name: "max-pycor", kind: "reporter", description: "Report the maximum y-coordinate of patches" },
    { name: "mean", kind: "reporter", description: "Report the mean of a list of numbers" },
    { name: "median", kind: "reporter", description: "Report the median of a list of numbers" },
    { name: "member?", kind: "reporter", description: "Report true if a value is in a list/string/agentset" },
    { name: "min", kind: "reporter", description: "Report the minimum value in a list" },
    { name: "min-n-of", kind: "reporter", description: "Report the N agents with lowest value" },
    { name: "min-one-of", kind: "reporter", description: "Report the agent with the lowest value" },
    { name: "min-pxcor", kind: "reporter", description: "Report the minimum x-coordinate of patches" },
    { name: "min-pycor", kind: "reporter", description: "Report the minimum y-coordinate of patches" },
    { name: "mod", kind: "reporter", description: "Report the remainder of a division" },
    { name: "modes", kind: "reporter", description: "Report the most common item(s) in a list" },
    { name: "mouse-down?", kind: "reporter", description: "Report true if the mouse button is down" },
    { name: "mouse-inside?", kind: "reporter", description: "Report true if the mouse is inside the view" },
    { name: "mouse-xcor", kind: "reporter", description: "Report the x-coordinate of the mouse" },
    { name: "mouse-ycor", kind: "reporter", description: "Report the y-coordinate of the mouse" },
    { name: "my-in-links", kind: "reporter", description: "Report agentset of directed links coming in" },
    { name: "my-links", kind: "reporter", description: "Report agentset of all links connected to this turtle" },
    { name: "my-out-links", kind: "reporter", description: "Report agentset of directed links going out" },
    { name: "myself", kind: "reporter", description: "Report the agent that asked the current agent" },
    { name: "n-of", kind: "reporter", description: "Report a random subset of N agents from an agentset" },
    { name: "n-values", kind: "reporter", description: "Report a list of N values generated by a reporter" },
    { name: "neighbors", kind: "reporter", description: "Report the 8 surrounding patches" },
    { name: "neighbors4", kind: "reporter", description: "Report the 4 surrounding patches" },
    { name: "netlogo-version", kind: "reporter", description: "Report the version of NetLogo" },
    { name: "netlogo-web?", kind: "reporter", description: "Report true if running in NetLogo Web" },
    { name: "new-seed", kind: "reporter", description: "Report a new random seed value" },
    { name: "no-links", kind: "reporter", description: "Report an empty link agentset" },
    { name: "no-patches", kind: "reporter", description: "Report an empty patch agentset" },
    { name: "no-turtles", kind: "reporter", description: "Report an empty turtle agentset" },
    { name: "not", kind: "reporter", description: "Logical NOT" },
    { name: "of", kind: "reporter", description: "Report the value of a variable or expression for agent(s)" },
    { name: "one-of", kind: "reporter", description: "Report a random item from a list or agentset" },
    { name: "or", kind: "reporter", description: "Logical OR of two boolean values" },
    { name: "other", kind: "reporter", description: "Report all agents in agentset except the caller" },
    { name: "other-end", kind: "reporter", description: "Report the other end of a link" },
    { name: "out-link-neighbor?", kind: "reporter", description: "Report true if there is a directed link to the other turtle" },
    { name: "out-link-neighbors", kind: "reporter", description: "Report agentset of turtles this turtle has directed links to" },
    { name: "out-link-to", kind: "reporter", description: "Report the directed link from this turtle to another" },
    { name: "patch", kind: "reporter", description: "Report the patch at coordinates (x, y)" },
    { name: "patch-ahead", kind: "reporter", description: "Report the patch ahead of the turtle by distance" },
    { name: "patch-at", kind: "reporter", description: "Report the patch at relative offset (dx, dy)" },
    { name: "patch-at-heading-and-distance", kind: "reporter", description: "Report the patch at a heading and distance" },
    { name: "patch-here", kind: "reporter", description: "Report the patch under this turtle" },
    { name: "patch-left-and-ahead", kind: "reporter", description: "Report the patch to the left and ahead" },
    { name: "patch-right-and-ahead", kind: "reporter", description: "Report the patch to the right and ahead" },
    { name: "patch-set", kind: "reporter", description: "Report an agentset of the given patches" },
    { name: "patch-size", kind: "reporter", description: "Report the size of patches in pixels" },
    { name: "patches", kind: "reporter", description: "Report the agentset of all patches" },
    { name: "plot-name", kind: "reporter", description: "Report the name of the current plot" },
    { name: "plot-pen-exists?", kind: "reporter", description: "Report true if the named pen exists" },
    { name: "plot-x-max", kind: "reporter", description: "Report the maximum x value of the current plot" },
    { name: "plot-x-min", kind: "reporter", description: "Report the minimum x value of the current plot" },
    { name: "plot-y-max", kind: "reporter", description: "Report the maximum y value of the current plot" },
    { name: "plot-y-min", kind: "reporter", description: "Report the minimum y value of the current plot" },
    { name: "position", kind: "reporter", description: "Report the index of a value in a list or string" },
    { name: "precision", kind: "reporter", description: "Report a number rounded to N decimal places" },
    { name: "random", kind: "reporter", description: "Report a random integer from 0 to N-1" },
    { name: "random-exponential", kind: "reporter", description: "Report a random exponentially distributed number" },
    { name: "random-float", kind: "reporter", description: "Report a random float from 0 to N" },
    { name: "random-gamma", kind: "reporter", description: "Report a random gamma-distributed number" },
    { name: "random-normal", kind: "reporter", description: "Report a random normally distributed number" },
    { name: "random-poisson", kind: "reporter", description: "Report a random Poisson-distributed number" },
    { name: "random-pxcor", kind: "reporter", description: "Report a random valid patch x-coordinate" },
    { name: "random-pycor", kind: "reporter", description: "Report a random valid patch y-coordinate" },
    { name: "random-xcor", kind: "reporter", description: "Report a random valid turtle x-coordinate" },
    { name: "random-ycor", kind: "reporter", description: "Report a random valid turtle y-coordinate" },
    { name: "range", kind: "reporter", description: "Report a list of numbers from start to end by step" },
    { name: "read-from-string", kind: "reporter", description: "Read a value from a string" },
    { name: "reduce", kind: "reporter", description: "Reduce a list to a single value using a reporter" },
    { name: "remainder", kind: "reporter", description: "Report the remainder of dividing two numbers" },
    { name: "remove", kind: "reporter", description: "Report a list/string with all occurrences of item removed" },
    { name: "remove-duplicates", kind: "reporter", description: "Report a list with duplicates removed" },
    { name: "remove-item", kind: "reporter", description: "Report a list/string with the item at index removed" },
    { name: "replace-item", kind: "reporter", description: "Report a list/string with item at index replaced" },
    { name: "reverse", kind: "reporter", description: "Report a reversed list or string" },
    { name: "rgb", kind: "reporter", description: "Report a color from RGB values" },
    { name: "round", kind: "reporter", description: "Report the nearest integer" },
    { name: "runresult", kind: "reporter", description: "Run a string or anonymous reporter and report the result" },
    { name: "scale-color", kind: "reporter", description: "Report a shade of a color scaled by a value" },
    { name: "self", kind: "reporter", description: "Report the current agent" },
    { name: "sentence", kind: "reporter", description: "Combine lists/values into a single list" },
    { name: "se", kind: "reporter", description: "Abbreviation for sentence" },
    { name: "shade-of?", kind: "reporter", description: "Report true if two colors are shades of each other" },
    { name: "shapes", kind: "reporter", description: "Report list of available turtle shapes" },
    { name: "shuffle", kind: "reporter", description: "Report a randomly reordered list" },
    { name: "sin", kind: "reporter", description: "Report the sine of an angle (in degrees)" },
    { name: "sort", kind: "reporter", description: "Report a sorted list" },
    { name: "sort-by", kind: "reporter", description: "Report a list sorted by a comparison reporter" },
    { name: "sort-on", kind: "reporter", description: "Report agents sorted by a reporter" },
    { name: "sqrt", kind: "reporter", description: "Report the square root" },
    { name: "standard-deviation", kind: "reporter", description: "Report the standard deviation of a list" },
    { name: "subject", kind: "reporter", description: "Report the agent being watched/followed/ridden" },
    { name: "sublist", kind: "reporter", description: "Report a portion of a list" },
    { name: "substring", kind: "reporter", description: "Report a portion of a string" },
    { name: "subtract-headings", kind: "reporter", description: "Report the difference between two headings" },
    { name: "sum", kind: "reporter", description: "Report the sum of a list of numbers" },
    { name: "tan", kind: "reporter", description: "Report the tangent of an angle (in degrees)" },
    { name: "ticks", kind: "reporter", description: "Report the current tick count" },
    { name: "timer", kind: "reporter", description: "Report the time since the timer was last reset" },
    { name: "towards", kind: "reporter", description: "Report the heading towards another agent" },
    { name: "towardsxy", kind: "reporter", description: "Report the heading towards a point (x, y)" },
    { name: "turtle", kind: "reporter", description: "Report the turtle with the given who number" },
    { name: "turtle-set", kind: "reporter", description: "Report an agentset of the given turtles" },
    { name: "turtles", kind: "reporter", description: "Report the agentset of all turtles" },
    { name: "turtles-at", kind: "reporter", description: "Report turtles at relative offset (dx, dy)" },
    { name: "turtles-here", kind: "reporter", description: "Report turtles on this patch" },
    { name: "turtles-on", kind: "reporter", description: "Report turtles on the same patch(es) as agent(s)" },
    { name: "up-to-n-of", kind: "reporter", description: "Report up to N random agents from an agentset" },
    { name: "user-directory", kind: "reporter", description: "Open a directory chooser dialog" },
    { name: "user-file", kind: "reporter", description: "Open a file chooser dialog" },
    { name: "user-input", kind: "reporter", description: "Show an input dialog and report the user's text" },
    { name: "user-new-file", kind: "reporter", description: "Open a save-file dialog" },
    { name: "user-one-of", kind: "reporter", description: "Show a chooser dialog and report the user's choice" },
    { name: "user-yes-or-no?", kind: "reporter", description: "Show a yes/no dialog and report the user's choice" },
    { name: "variance", kind: "reporter", description: "Report the variance of a list of numbers" },
    { name: "with", kind: "reporter", description: "Report agents in agentset satisfying a condition" },
    { name: "with-max", kind: "reporter", description: "Report agent(s) with the maximum value of a reporter" },
    { name: "with-min", kind: "reporter", description: "Report agent(s) with the minimum value of a reporter" },
    { name: "word", kind: "reporter", description: "Concatenate values into a single string" },
    { name: "world-height", kind: "reporter", description: "Report the total height of the world in patches" },
    { name: "world-width", kind: "reporter", description: "Report the total width of the world in patches" },
    { name: "wrap-color", kind: "reporter", description: "Report a color value wrapped to 0-140 range" },
    { name: "xor", kind: "reporter", description: "Logical exclusive OR" },
];
/** All built-in primitives combined */
export const ALL_BUILTINS: Builtin[] = [
    ...KEYWORDS,
    ...CONSTANTS,
    ...COMMANDS,
    ...REPORTERS,
];
/** Quick lookup by lowercase name */
const builtinMap = new Map<string, Builtin>();
for (const b of ALL_BUILTINS) {
    builtinMap.set(b.name.toLowerCase(), b);
}
export function lookupBuiltin(name: string): Builtin | undefined {
    return builtinMap.get(name.toLowerCase());
}
